# Android
# Build your Android project with Gradle.
# Add steps that test, sign, and distribute the APK, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/android

trigger:
- master

pool:
  vmImage: 'macos-latest'

jobs:
- job: ANDROID
  displayName: Build_Android_APK
  pool:
    name: AndroidBuilder
  steps:
  - checkout: self
  - task: FlutterInstall@0
    inputs:
      mode: 'auto'
      channel: 'stable'
      version: 'custom'
      customVersion: '3.7.12'
  - task: CmdLine@2
    displayName: Upgrade & clean Flutter
    inputs:
      script: |
        $(FlutterToolPath)/flutter clean \
        cd ios \
        pod deintegrate \
        rm Flutter/Flutter.podspec \
        rm podfile.lock \
