name: Android test
on:
  pull_request:
    branches: [ master ]
    
jobs:
  test:
    runs-on: ubuntu-lastest
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: run Unit Test
        run: ./gradlew cAT
      - uses: actions/upload-artifact@v3
        with:
          name: Package
          path: app/build/reports/androidTests/connected/index.html
